#!/usr/bin/env ruby
# Fetch Google's hardware attestation root certificates and concatenate them
# into app/src/main/assets/google_attestation_roots.pem.
#
# Source of truth:
#   https://developer.android.com/training/articles/security-key-attestation#root_certificate
#
# The page embeds each root cert inline as a PEM block. We download the page,
# extract every BEGIN CERTIFICATE / END CERTIFICATE block, sanity-check the
# count, then write the bundle.
#
# Run: ruby scripts/fetch_attestation_roots.rb
# Re-run quarterly, or whenever Google announces a new attestation root.
#
# This script has no external gem dependencies — only Ruby stdlib.

require 'net/http'
require 'uri'
require 'openssl'
require 'fileutils'

DOC_URL = URI('https://developer.android.com/training/articles/security-key-attestation')
OUTPUT  = File.expand_path('../app/src/main/assets/google_attestation_roots.pem', __dir__)

# Historical minimum count of known Google attestation roots. If fewer are
# extracted the page format probably changed; bail out rather than ship a
# partial bundle that silently rejects valid devices.
MIN_EXPECTED_ROOTS = 4

def fetch(uri, redirects_left = 5)
  raise 'too many redirects' if redirects_left.negative?

  Net::HTTP.start(uri.host, uri.port, use_ssl: uri.scheme == 'https') do |http|
    response = http.get(uri.request_uri, 'User-Agent' => 'psdk-attestation-fetch/1.0')
    case response
    when Net::HTTPSuccess
      response.body
    when Net::HTTPRedirection
      # Location may be absolute or relative — URI.join handles both.
      fetch(URI.join(uri, response['Location']), redirects_left - 1)
    else
      raise "HTTP #{response.code} fetching #{uri}"
    end
  end
end

def extract_pem_blocks(html)
  # Google's documentation HTML wraps each cert in <pre> ... </pre>. We don't
  # need to parse HTML — the PEM markers are unambiguous.
  html.scan(/-----BEGIN CERTIFICATE-----.*?-----END CERTIFICATE-----/m).map do |block|
    # Strip any HTML entities that might have crept in.
    block.gsub('&amp;', '&')
         .gsub('&lt;', '<')
         .gsub('&gt;', '>')
         .gsub(/<[^>]+>/, '')
         .strip
  end
end

def validate_pem(pem)
  cert = OpenSSL::X509::Certificate.new(pem)
  cert.subject.to_s
end

puts "Fetching #{DOC_URL}..."
html = fetch(DOC_URL)
puts "  page size: #{html.bytesize} bytes"

blocks = extract_pem_blocks(html).uniq
puts "  found #{blocks.size} unique PEM blocks"

if blocks.size < MIN_EXPECTED_ROOTS
  warn ''
  warn "ERROR: extracted only #{blocks.size} cert(s); expected at least #{MIN_EXPECTED_ROOTS}."
  warn "The documentation page format probably changed. Open #{DOC_URL} in a"
  warn 'browser, copy the certificates manually into:'
  warn "  #{OUTPUT}"
  exit 1
end

# Validate each block parses as a real X.509 certificate before we write.
blocks.each_with_index do |pem, i|
  begin
    subject = validate_pem(pem)
    puts "  [#{i}] OK  #{subject[0, 80]}"
  rescue OpenSSL::X509::CertificateError => e
    warn "ERROR: block #{i} is not a valid X.509 certificate: #{e.message}"
    exit 1
  end
end

FileUtils.mkdir_p(File.dirname(OUTPUT))
header = <<~HEADER
  -- Google Hardware Attestation Root Certificates
  --
  -- Auto-generated by scripts/fetch_attestation_roots.rb
  -- Source: #{DOC_URL}
  -- Generated: #{Time.now.utc.iso8601}
  --
  -- Re-run the fetch script quarterly or when Google announces a new attestation root.
  -- KeyAttestationGate.verifyRootIsGoogle() matches incoming attestations against
  -- the public keys in this bundle.

HEADER

File.write(OUTPUT, header + blocks.join("\n\n") + "\n")
puts ""
puts "Wrote #{blocks.size} certificate(s) to #{OUTPUT}"
puts "  size: #{File.size(OUTPUT)} bytes"
